// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jemsuskxhiswkejqcbsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplbXN1c2t4aGlzd2tlanFjYnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzE2NDksImV4cCI6MjA2ODUwNzY0OX0.JdrNTXyw55gH9HdZYVG7QVDn_-_iHqeD9eDns79-Jy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});